# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-12 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dreamcode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('problem', models.TextField(default='')),
                ('submission_template', models.TextField(default='')),
                ('score', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NT', 'Untested'), ('CE', 'Compile Error'), ('PD', 'Pending'), ('TS', 'Tested')], default='NT', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(editable=False)),
                ('score_percentage', models.IntegerField(default=-1)),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamcode.Challenge')),
            ],
            options={
                'ordering': ['-modified'],
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'permissions': (('can_test_submission', 'Can test submission'),),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(help_text='Input or mandatory', upload_to=dreamcode.models.testcasein_upload_path)),
                ('output', models.FileField(help_text='Output or deny', upload_to=dreamcode.models.testcaseout_upload_path)),
                ('cpu_time_limit', models.IntegerField(default=2000)),
                ('wallclock_time_limit', models.IntegerField(default=6000)),
                ('memory_limit', models.IntegerField(default=8388608)),
                ('disk_limit', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('hint', models.TextField(blank=True, default='', help_text='Only the first line is shown in hint. If test case is public, hint is appended to the challenge text.')),
                ('type', models.CharField(choices=[('IO', 'Input - Output'), ('MD', 'Mandatory - Denied')], default='IO', max_length=2)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamcode.Challenge')),
            ],
            options={
                'ordering': ['-is_public'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OK', 'Okay'), ('RF', 'Restricted Function'), ('ML', 'Memory Limit Exceed'), ('OL', 'Output Limit Exceed'), ('TL', 'Time Limit Exceed'), ('RT', 'Run Time Error (SIGSEGV, SIGFPE, ...)'), ('AT', 'Abnormal Termination'), ('IE', 'Internal Error (of sandbox executor)'), ('BP', 'Bad Policy'), ('R0', 'Reserved result type 0'), ('R1', 'Reserved result type 1'), ('R2', 'Reserved result type 2'), ('R3', 'Reserved result type 3'), ('R4', 'Reserved result type 4'), ('R5', 'Reserved result type 5'), ('EX', 'Exception')], default='PD', max_length=2)),
                ('memory', models.IntegerField(default=0)),
                ('cputime', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('PD', 'Pending'), ('OK', 'Accepted'), ('PE', 'Presentation error'), ('FA', 'Failed')], default='PD', max_length=2)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='dreamcode.Submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='dreamcode.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamcode.Contest'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set([('submission', 'test_case')]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('author', 'challenge')]),
        ),
    ]
