# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dreamcode.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='contest',
            field=models.ForeignKey(default=dreamcode.models.get_or_create_default_contest, on_delete=django.db.models.deletion.CASCADE, to='dreamcode.Contest'),
        ),
    ]
