# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-13 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0002_auto_20171213_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 5, 46, 55, 154341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 5, 46, 55, 154281, tzinfo=utc)),
        ),
    ]
