# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-12 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0002_auto_20171212_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 4, 9, 33, 471086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 4, 9, 33, 471038, tzinfo=utc)),
        ),
    ]
