# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-12 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0003_auto_20171212_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission_template',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 5, 36, 42, 20992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 5, 36, 42, 20944, tzinfo=utc)),
        ),
    ]
