# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-13 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0006_auto_20171212_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 4, 48, 8, 755747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 4, 48, 8, 755692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.CharField(choices=[('PD', 'Pending'), ('OK', 'Accepted'), ('FA', 'FAILED')], default='PD', max_length=2),
        ),
    ]
