# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcode', '0011_auto_20171213_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 1, 11, 30, 382941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 1, 11, 30, 382894, tzinfo=utc)),
        ),
    ]
