# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': ('can_test_submission', 'Can test submission')},
        ),
        migrations.AddField(
            model_name='problem',
            name='submission_template',
            field=models.TextField(default=''),
        ),
    ]
