# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-11 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 51, 22, 873226, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 51, 22, 873180, tzinfo=utc)),
        ),
    ]
