# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-11 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0002_auto_20171211_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 29, 30, 259637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 29, 30, 259591, tzinfo=utc)),
        ),
    ]
