# Generated by Django 2.0 on 2017-12-11 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import ejudge.models


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0002_auto_20171211_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 32, 4, 930227, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 32, 4, 930188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(default=ejudge.models.get_or_create_default_contest, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejudge.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('NT', 'Not Tested'), ('CE', 'Compile Error'), ('PD', 'Pending'), ('TS', 'Tested')], default='NT', max_length=2),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('IO', 'Input - Output'), ('MD', 'Mandatory - Denied')], default='IO', max_length=2),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.CharField(choices=[('PD', 'Pending'), ('OK', 'Accepted'), ('PE', 'Presentation error'), ('FA', 'Failed')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('OK', 'Okay'), ('RF', 'Restricted Function'), ('ML', 'Memory Limit Exceed'), ('OL', 'Output Limit Exceed'), ('TL', 'Time Limit Exceed'), ('RT', 'Run Time Error (SIGSEGV, SIGFPE, ...)'), ('AT', 'Abnormal Termination'), ('IE', 'Internal Error (of sandbox executor)'), ('BP', 'Bad Policy'), ('R0', 'Reserved result type 0'), ('R1', 'Reserved result type 1'), ('R2', 'Reserved result type 2'), ('R3', 'Reserved result type 3'), ('R4', 'Reserved result type 4'), ('R5', 'Reserved result type 5'), ('EX', 'Exception')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='task_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
