# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0002_auto_20171211_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
    ]
