# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0003_auto_20171211_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': (('can_test_submission', 'Can test submission'),)},
        ),
    ]
