# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-11 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0003_auto_20171211_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 33, 12, 508834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 33, 12, 508785, tzinfo=utc)),
        ),
    ]
